### ISSUE TITLE
S1-PBI 1 Guest dapat mendaftarkan diri pada website SIPADU

### ISSUE THREAD

**Issue by DanarPrayoga** [SI-RPL-2022/SI4304_F_SIPADU#1]

**Comment by DanarPrayoga** [comment]
![image](https://user-images.githubusercontent.com/91936761/161499894-6a0c9d99-c973-4ba3-a1ee-9b32e959b7d2.png)
Tampilan awal website

**Comment by DanarPrayoga** [comment]
![image](https://user-images.githubusercontent.com/91936761/161915495-ebd4db5e-8890-47bc-b9a4-f950277f8ec9.png)
tampilan halaman register

**Comment by itsnaufal** [comment]
Fungsi register sudah selesai
